export declare class SftpPacket {
    static INIT: number;
    static VERSION: number;
    static REQUEST_MIN: number;
    static OPEN: number;
    static CLOSE: number;
    static READ: number;
    static WRITE: number;
    static LSTAT: number;
    static FSTAT: number;
    static SETSTAT: number;
    static FSETSTAT: number;
    static OPENDIR: number;
    static READDIR: number;
    static REMOVE: number;
    static MKDIR: number;
    static RMDIR: number;
    static REALPATH: number;
    static STAT: number;
    static RENAME: number;
    static READLINK: number;
    static SYMLINK: number;
    static REQUEST_MAX: number;
    static STATUS: number;
    static HANDLE: number;
    static DATA: number;
    static NAME: number;
    static ATTRS: number;
    public buffer: NodeBuffer;
    public offset: number;
    public length: number;
    constructor(buffer: NodeBuffer);
    public reset(): void;
    public seek(offset: number): void;
    public ignore(count: number): number;
    public writeByte(value: number): void;
    public writeInt32(value: number): void;
    public writeInt64(value: number): void;
    public writeString(value: string): void;
    private checkSize(size);
    public readByte(): number;
    public readInt32(): number;
    public readUint32(): number;
    public readInt64(): number;
    public readString(): string;
    public skipString(): void;
    public writeHandle(h: number): void;
    public readHandle(): any;
    public isEmpty(): boolean;
}
